// source: Message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Msg_pb = require('./Msg_pb.js');
goog.object.extend(proto, Msg_pb);
var OpCode_pb = require('./OpCode_pb.js');
goog.object.extend(proto, OpCode_pb);
var Connection_pb = require('./Connection_pb.js');
goog.object.extend(proto, Connection_pb);
var Auth_pb = require('./Auth_pb.js');
goog.object.extend(proto, Auth_pb);
var Group_pb = require('./Group_pb.js');
goog.object.extend(proto, Group_pb);
var Invitation_pb = require('./Invitation_pb.js');
goog.object.extend(proto, Invitation_pb);
var Friend_pb = require('./Friend_pb.js');
goog.object.extend(proto, Friend_pb);
goog.exportSymbol('proto.Message', null, global);
goog.exportSymbol('proto.Message.PayloadCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, proto.Message.oneofGroups_);
};
goog.inherits(proto.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Message.displayName = 'proto.Message';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Message.oneofGroups_ = [[11,12,20,23,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010]];

/**
 * @enum {number}
 */
proto.Message.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  AUTH_REQUEST: 11,
  AUTH_ACK: 12,
  MSG_REQUEST: 20,
  MSG_ACK: 23,
  QUERY_USER_GROUP_REQUEST: 21,
  QUERY_USER_GROUP_ACK: 22,
  ASK_FOR_JOIN_GROUP_REQUEST: 24,
  ASK_FOR_JOIN_GROUP_ACK: 25,
  INVITATION_JOIN_GROUP_REQUEST: 26,
  INVITATION_JOIN_GROUP_ACK: 27,
  CREATE_GROUP_REQUEST: 28,
  CREATE_GROUP_ACK: 29,
  REMOVE_GROUP_MEMBER_REQUEST: 30,
  REMOVE_GROUP_MEMBER_ACK: 31,
  CHANGE_GROUP_NAME_REQUEST: 32,
  CHANGE_GROUP_NAME_ACK: 33,
  CHANGE_GROUP_NOTICE_REQUEST: 34,
  CHANGE_GROUP_NOTICE_ACK: 35,
  CHANGE_MUC_MUTE_REQUEST: 36,
  CHANGE_MUC_MUTE_ACK: 37,
  CHANGE_MUC_CONFIRM_JOIN_REQUEST: 38,
  CHANGE_MUC_CONFIRM_JOIN_ACK: 39,
  EXIT_GROUP_REQUEST: 40,
  EXIT_GROUP_ACK: 41,
  INVITATION_REQUEST_REQUEST: 1001,
  INVITATION_REQUEST_ACK: 1002,
  INVITATION_ACCEPT_REQUEST: 1003,
  INVITATION_ACCEPT_ACK: 1004,
  INVITATION_DECLINED_REQUEST: 1005,
  INVITATION_DECLINED_ACK: 1006,
  INVITATION_REQUEST: 1007,
  INVITATION_ACK: 1008,
  FRIEND_REQUEST: 1009,
  FRIEND_ACK: 1010
};

/**
 * @return {proto.Message.PayloadCase}
 */
proto.Message.prototype.getPayloadCase = function() {
  return /** @type {proto.Message.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.Message.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    magic: jspb.Message.getFieldWithDefault(msg, 1, "0"),
    version: jspb.Message.getFieldWithDefault(msg, 2, 0),
    opCode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    seq: jspb.Message.getFieldWithDefault(msg, 4, "0"),
    authRequest: (f = msg.getAuthRequest()) && Auth_pb.AuthRequest.toObject(includeInstance, f),
    authAck: (f = msg.getAuthAck()) && Auth_pb.AuthAck.toObject(includeInstance, f),
    msgRequest: (f = msg.getMsgRequest()) && Msg_pb.MsgRequest.toObject(includeInstance, f),
    msgAck: (f = msg.getMsgAck()) && Msg_pb.MsgAck.toObject(includeInstance, f),
    queryUserGroupRequest: (f = msg.getQueryUserGroupRequest()) && Group_pb.QueryUserGroupsRequest.toObject(includeInstance, f),
    queryUserGroupAck: (f = msg.getQueryUserGroupAck()) && Group_pb.QueryUserGroupsAck.toObject(includeInstance, f),
    askForJoinGroupRequest: (f = msg.getAskForJoinGroupRequest()) && Group_pb.AskFroJoinGroupRequest.toObject(includeInstance, f),
    askForJoinGroupAck: (f = msg.getAskForJoinGroupAck()) && Group_pb.AskForJoinGroupAck.toObject(includeInstance, f),
    invitationJoinGroupRequest: (f = msg.getInvitationJoinGroupRequest()) && Group_pb.InvitationJoinGroupRequest.toObject(includeInstance, f),
    invitationJoinGroupAck: (f = msg.getInvitationJoinGroupAck()) && Group_pb.InvitationJoinGroupAck.toObject(includeInstance, f),
    createGroupRequest: (f = msg.getCreateGroupRequest()) && Group_pb.CreateGroupRequest.toObject(includeInstance, f),
    createGroupAck: (f = msg.getCreateGroupAck()) && Group_pb.CreateGroupAck.toObject(includeInstance, f),
    removeGroupMemberRequest: (f = msg.getRemoveGroupMemberRequest()) && Group_pb.RemoveGroupMemberRequest.toObject(includeInstance, f),
    removeGroupMemberAck: (f = msg.getRemoveGroupMemberAck()) && Group_pb.RemoveGroupMemberAck.toObject(includeInstance, f),
    changeGroupNameRequest: (f = msg.getChangeGroupNameRequest()) && Group_pb.ChangeGroupNameRequest.toObject(includeInstance, f),
    changeGroupNameAck: (f = msg.getChangeGroupNameAck()) && Group_pb.ChangeGroupNameAck.toObject(includeInstance, f),
    changeGroupNoticeRequest: (f = msg.getChangeGroupNoticeRequest()) && Group_pb.ChangeGroupNoticeRequest.toObject(includeInstance, f),
    changeGroupNoticeAck: (f = msg.getChangeGroupNoticeAck()) && Group_pb.ChangeGroupNoticeAck.toObject(includeInstance, f),
    changeMucMuteRequest: (f = msg.getChangeMucMuteRequest()) && Group_pb.ChangeMucMuteRequest.toObject(includeInstance, f),
    changeMucMuteAck: (f = msg.getChangeMucMuteAck()) && Group_pb.ChangeMucMuteAck.toObject(includeInstance, f),
    changeMucConfirmJoinRequest: (f = msg.getChangeMucConfirmJoinRequest()) && Group_pb.ChangeMucConfirmJoinRequest.toObject(includeInstance, f),
    changeMucConfirmJoinAck: (f = msg.getChangeMucConfirmJoinAck()) && Group_pb.ChangeMucConfirmJoinAck.toObject(includeInstance, f),
    exitGroupRequest: (f = msg.getExitGroupRequest()) && Group_pb.ExitGroupRequest.toObject(includeInstance, f),
    exitGroupAck: (f = msg.getExitGroupAck()) && Group_pb.ExitGroupAck.toObject(includeInstance, f),
    invitationRequestRequest: (f = msg.getInvitationRequestRequest()) && Invitation_pb.InvitationRequestRequest.toObject(includeInstance, f),
    invitationRequestAck: (f = msg.getInvitationRequestAck()) && Invitation_pb.InvitationRequestAck.toObject(includeInstance, f),
    invitationAcceptRequest: (f = msg.getInvitationAcceptRequest()) && Invitation_pb.InvitationAcceptRequest.toObject(includeInstance, f),
    invitationAcceptAck: (f = msg.getInvitationAcceptAck()) && Invitation_pb.InvitationAcceptAck.toObject(includeInstance, f),
    invitationDeclinedRequest: (f = msg.getInvitationDeclinedRequest()) && Invitation_pb.InvitationDeclinedRequest.toObject(includeInstance, f),
    invitationDeclinedAck: (f = msg.getInvitationDeclinedAck()) && Invitation_pb.InvitationDeclinedAck.toObject(includeInstance, f),
    invitationRequest: (f = msg.getInvitationRequest()) && Invitation_pb.InvitationRequest.toObject(includeInstance, f),
    invitationAck: (f = msg.getInvitationAck()) && Invitation_pb.InvitationAck.toObject(includeInstance, f),
    friendRequest: (f = msg.getFriendRequest()) && Friend_pb.FriendRequest.toObject(includeInstance, f),
    friendAck: (f = msg.getFriendAck()) && Friend_pb.FriendAck.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Message;
  return proto.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readUint64String());
      msg.setMagic(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {!proto.OpCode} */ (reader.readEnum());
      msg.setOpCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readUint64String());
      msg.setSeq(value);
      break;
    case 11:
      var value = new Auth_pb.AuthRequest;
      reader.readMessage(value,Auth_pb.AuthRequest.deserializeBinaryFromReader);
      msg.setAuthRequest(value);
      break;
    case 12:
      var value = new Auth_pb.AuthAck;
      reader.readMessage(value,Auth_pb.AuthAck.deserializeBinaryFromReader);
      msg.setAuthAck(value);
      break;
    case 20:
      var value = new Msg_pb.MsgRequest;
      reader.readMessage(value,Msg_pb.MsgRequest.deserializeBinaryFromReader);
      msg.setMsgRequest(value);
      break;
    case 23:
      var value = new Msg_pb.MsgAck;
      reader.readMessage(value,Msg_pb.MsgAck.deserializeBinaryFromReader);
      msg.setMsgAck(value);
      break;
    case 21:
      var value = new Group_pb.QueryUserGroupsRequest;
      reader.readMessage(value,Group_pb.QueryUserGroupsRequest.deserializeBinaryFromReader);
      msg.setQueryUserGroupRequest(value);
      break;
    case 22:
      var value = new Group_pb.QueryUserGroupsAck;
      reader.readMessage(value,Group_pb.QueryUserGroupsAck.deserializeBinaryFromReader);
      msg.setQueryUserGroupAck(value);
      break;
    case 24:
      var value = new Group_pb.AskFroJoinGroupRequest;
      reader.readMessage(value,Group_pb.AskFroJoinGroupRequest.deserializeBinaryFromReader);
      msg.setAskForJoinGroupRequest(value);
      break;
    case 25:
      var value = new Group_pb.AskForJoinGroupAck;
      reader.readMessage(value,Group_pb.AskForJoinGroupAck.deserializeBinaryFromReader);
      msg.setAskForJoinGroupAck(value);
      break;
    case 26:
      var value = new Group_pb.InvitationJoinGroupRequest;
      reader.readMessage(value,Group_pb.InvitationJoinGroupRequest.deserializeBinaryFromReader);
      msg.setInvitationJoinGroupRequest(value);
      break;
    case 27:
      var value = new Group_pb.InvitationJoinGroupAck;
      reader.readMessage(value,Group_pb.InvitationJoinGroupAck.deserializeBinaryFromReader);
      msg.setInvitationJoinGroupAck(value);
      break;
    case 28:
      var value = new Group_pb.CreateGroupRequest;
      reader.readMessage(value,Group_pb.CreateGroupRequest.deserializeBinaryFromReader);
      msg.setCreateGroupRequest(value);
      break;
    case 29:
      var value = new Group_pb.CreateGroupAck;
      reader.readMessage(value,Group_pb.CreateGroupAck.deserializeBinaryFromReader);
      msg.setCreateGroupAck(value);
      break;
    case 30:
      var value = new Group_pb.RemoveGroupMemberRequest;
      reader.readMessage(value,Group_pb.RemoveGroupMemberRequest.deserializeBinaryFromReader);
      msg.setRemoveGroupMemberRequest(value);
      break;
    case 31:
      var value = new Group_pb.RemoveGroupMemberAck;
      reader.readMessage(value,Group_pb.RemoveGroupMemberAck.deserializeBinaryFromReader);
      msg.setRemoveGroupMemberAck(value);
      break;
    case 32:
      var value = new Group_pb.ChangeGroupNameRequest;
      reader.readMessage(value,Group_pb.ChangeGroupNameRequest.deserializeBinaryFromReader);
      msg.setChangeGroupNameRequest(value);
      break;
    case 33:
      var value = new Group_pb.ChangeGroupNameAck;
      reader.readMessage(value,Group_pb.ChangeGroupNameAck.deserializeBinaryFromReader);
      msg.setChangeGroupNameAck(value);
      break;
    case 34:
      var value = new Group_pb.ChangeGroupNoticeRequest;
      reader.readMessage(value,Group_pb.ChangeGroupNoticeRequest.deserializeBinaryFromReader);
      msg.setChangeGroupNoticeRequest(value);
      break;
    case 35:
      var value = new Group_pb.ChangeGroupNoticeAck;
      reader.readMessage(value,Group_pb.ChangeGroupNoticeAck.deserializeBinaryFromReader);
      msg.setChangeGroupNoticeAck(value);
      break;
    case 36:
      var value = new Group_pb.ChangeMucMuteRequest;
      reader.readMessage(value,Group_pb.ChangeMucMuteRequest.deserializeBinaryFromReader);
      msg.setChangeMucMuteRequest(value);
      break;
    case 37:
      var value = new Group_pb.ChangeMucMuteAck;
      reader.readMessage(value,Group_pb.ChangeMucMuteAck.deserializeBinaryFromReader);
      msg.setChangeMucMuteAck(value);
      break;
    case 38:
      var value = new Group_pb.ChangeMucConfirmJoinRequest;
      reader.readMessage(value,Group_pb.ChangeMucConfirmJoinRequest.deserializeBinaryFromReader);
      msg.setChangeMucConfirmJoinRequest(value);
      break;
    case 39:
      var value = new Group_pb.ChangeMucConfirmJoinAck;
      reader.readMessage(value,Group_pb.ChangeMucConfirmJoinAck.deserializeBinaryFromReader);
      msg.setChangeMucConfirmJoinAck(value);
      break;
    case 40:
      var value = new Group_pb.ExitGroupRequest;
      reader.readMessage(value,Group_pb.ExitGroupRequest.deserializeBinaryFromReader);
      msg.setExitGroupRequest(value);
      break;
    case 41:
      var value = new Group_pb.ExitGroupAck;
      reader.readMessage(value,Group_pb.ExitGroupAck.deserializeBinaryFromReader);
      msg.setExitGroupAck(value);
      break;
    case 1001:
      var value = new Invitation_pb.InvitationRequestRequest;
      reader.readMessage(value,Invitation_pb.InvitationRequestRequest.deserializeBinaryFromReader);
      msg.setInvitationRequestRequest(value);
      break;
    case 1002:
      var value = new Invitation_pb.InvitationRequestAck;
      reader.readMessage(value,Invitation_pb.InvitationRequestAck.deserializeBinaryFromReader);
      msg.setInvitationRequestAck(value);
      break;
    case 1003:
      var value = new Invitation_pb.InvitationAcceptRequest;
      reader.readMessage(value,Invitation_pb.InvitationAcceptRequest.deserializeBinaryFromReader);
      msg.setInvitationAcceptRequest(value);
      break;
    case 1004:
      var value = new Invitation_pb.InvitationAcceptAck;
      reader.readMessage(value,Invitation_pb.InvitationAcceptAck.deserializeBinaryFromReader);
      msg.setInvitationAcceptAck(value);
      break;
    case 1005:
      var value = new Invitation_pb.InvitationDeclinedRequest;
      reader.readMessage(value,Invitation_pb.InvitationDeclinedRequest.deserializeBinaryFromReader);
      msg.setInvitationDeclinedRequest(value);
      break;
    case 1006:
      var value = new Invitation_pb.InvitationDeclinedAck;
      reader.readMessage(value,Invitation_pb.InvitationDeclinedAck.deserializeBinaryFromReader);
      msg.setInvitationDeclinedAck(value);
      break;
    case 1007:
      var value = new Invitation_pb.InvitationRequest;
      reader.readMessage(value,Invitation_pb.InvitationRequest.deserializeBinaryFromReader);
      msg.setInvitationRequest(value);
      break;
    case 1008:
      var value = new Invitation_pb.InvitationAck;
      reader.readMessage(value,Invitation_pb.InvitationAck.deserializeBinaryFromReader);
      msg.setInvitationAck(value);
      break;
    case 1009:
      var value = new Friend_pb.FriendRequest;
      reader.readMessage(value,Friend_pb.FriendRequest.deserializeBinaryFromReader);
      msg.setFriendRequest(value);
      break;
    case 1010:
      var value = new Friend_pb.FriendAck;
      reader.readMessage(value,Friend_pb.FriendAck.deserializeBinaryFromReader);
      msg.setFriendAck(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMagic();
  if (parseInt(f, 10) !== 0) {
    writer.writeUint64String(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getOpCode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSeq();
  if (parseInt(f, 10) !== 0) {
    writer.writeUint64String(
      4,
      f
    );
  }
  f = message.getAuthRequest();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      Auth_pb.AuthRequest.serializeBinaryToWriter
    );
  }
  f = message.getAuthAck();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      Auth_pb.AuthAck.serializeBinaryToWriter
    );
  }
  f = message.getMsgRequest();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      Msg_pb.MsgRequest.serializeBinaryToWriter
    );
  }
  f = message.getMsgAck();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      Msg_pb.MsgAck.serializeBinaryToWriter
    );
  }
  f = message.getQueryUserGroupRequest();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      Group_pb.QueryUserGroupsRequest.serializeBinaryToWriter
    );
  }
  f = message.getQueryUserGroupAck();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      Group_pb.QueryUserGroupsAck.serializeBinaryToWriter
    );
  }
  f = message.getAskForJoinGroupRequest();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      Group_pb.AskFroJoinGroupRequest.serializeBinaryToWriter
    );
  }
  f = message.getAskForJoinGroupAck();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      Group_pb.AskForJoinGroupAck.serializeBinaryToWriter
    );
  }
  f = message.getInvitationJoinGroupRequest();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      Group_pb.InvitationJoinGroupRequest.serializeBinaryToWriter
    );
  }
  f = message.getInvitationJoinGroupAck();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      Group_pb.InvitationJoinGroupAck.serializeBinaryToWriter
    );
  }
  f = message.getCreateGroupRequest();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      Group_pb.CreateGroupRequest.serializeBinaryToWriter
    );
  }
  f = message.getCreateGroupAck();
  if (f != null) {
    writer.writeMessage(
      29,
      f,
      Group_pb.CreateGroupAck.serializeBinaryToWriter
    );
  }
  f = message.getRemoveGroupMemberRequest();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      Group_pb.RemoveGroupMemberRequest.serializeBinaryToWriter
    );
  }
  f = message.getRemoveGroupMemberAck();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      Group_pb.RemoveGroupMemberAck.serializeBinaryToWriter
    );
  }
  f = message.getChangeGroupNameRequest();
  if (f != null) {
    writer.writeMessage(
      32,
      f,
      Group_pb.ChangeGroupNameRequest.serializeBinaryToWriter
    );
  }
  f = message.getChangeGroupNameAck();
  if (f != null) {
    writer.writeMessage(
      33,
      f,
      Group_pb.ChangeGroupNameAck.serializeBinaryToWriter
    );
  }
  f = message.getChangeGroupNoticeRequest();
  if (f != null) {
    writer.writeMessage(
      34,
      f,
      Group_pb.ChangeGroupNoticeRequest.serializeBinaryToWriter
    );
  }
  f = message.getChangeGroupNoticeAck();
  if (f != null) {
    writer.writeMessage(
      35,
      f,
      Group_pb.ChangeGroupNoticeAck.serializeBinaryToWriter
    );
  }
  f = message.getChangeMucMuteRequest();
  if (f != null) {
    writer.writeMessage(
      36,
      f,
      Group_pb.ChangeMucMuteRequest.serializeBinaryToWriter
    );
  }
  f = message.getChangeMucMuteAck();
  if (f != null) {
    writer.writeMessage(
      37,
      f,
      Group_pb.ChangeMucMuteAck.serializeBinaryToWriter
    );
  }
  f = message.getChangeMucConfirmJoinRequest();
  if (f != null) {
    writer.writeMessage(
      38,
      f,
      Group_pb.ChangeMucConfirmJoinRequest.serializeBinaryToWriter
    );
  }
  f = message.getChangeMucConfirmJoinAck();
  if (f != null) {
    writer.writeMessage(
      39,
      f,
      Group_pb.ChangeMucConfirmJoinAck.serializeBinaryToWriter
    );
  }
  f = message.getExitGroupRequest();
  if (f != null) {
    writer.writeMessage(
      40,
      f,
      Group_pb.ExitGroupRequest.serializeBinaryToWriter
    );
  }
  f = message.getExitGroupAck();
  if (f != null) {
    writer.writeMessage(
      41,
      f,
      Group_pb.ExitGroupAck.serializeBinaryToWriter
    );
  }
  f = message.getInvitationRequestRequest();
  if (f != null) {
    writer.writeMessage(
      1001,
      f,
      Invitation_pb.InvitationRequestRequest.serializeBinaryToWriter
    );
  }
  f = message.getInvitationRequestAck();
  if (f != null) {
    writer.writeMessage(
      1002,
      f,
      Invitation_pb.InvitationRequestAck.serializeBinaryToWriter
    );
  }
  f = message.getInvitationAcceptRequest();
  if (f != null) {
    writer.writeMessage(
      1003,
      f,
      Invitation_pb.InvitationAcceptRequest.serializeBinaryToWriter
    );
  }
  f = message.getInvitationAcceptAck();
  if (f != null) {
    writer.writeMessage(
      1004,
      f,
      Invitation_pb.InvitationAcceptAck.serializeBinaryToWriter
    );
  }
  f = message.getInvitationDeclinedRequest();
  if (f != null) {
    writer.writeMessage(
      1005,
      f,
      Invitation_pb.InvitationDeclinedRequest.serializeBinaryToWriter
    );
  }
  f = message.getInvitationDeclinedAck();
  if (f != null) {
    writer.writeMessage(
      1006,
      f,
      Invitation_pb.InvitationDeclinedAck.serializeBinaryToWriter
    );
  }
  f = message.getInvitationRequest();
  if (f != null) {
    writer.writeMessage(
      1007,
      f,
      Invitation_pb.InvitationRequest.serializeBinaryToWriter
    );
  }
  f = message.getInvitationAck();
  if (f != null) {
    writer.writeMessage(
      1008,
      f,
      Invitation_pb.InvitationAck.serializeBinaryToWriter
    );
  }
  f = message.getFriendRequest();
  if (f != null) {
    writer.writeMessage(
      1009,
      f,
      Friend_pb.FriendRequest.serializeBinaryToWriter
    );
  }
  f = message.getFriendAck();
  if (f != null) {
    writer.writeMessage(
      1010,
      f,
      Friend_pb.FriendAck.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 magic = 1;
 * @return {string}
 */
proto.Message.prototype.getMagic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, "0"));
};


/**
 * @param {string} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setMagic = function(value) {
  return jspb.Message.setProto3StringIntField(this, 1, value);
};


/**
 * optional uint32 version = 2;
 * @return {number}
 */
proto.Message.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional OpCode op_code = 3;
 * @return {!proto.OpCode}
 */
proto.Message.prototype.getOpCode = function() {
  return /** @type {!proto.OpCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.OpCode} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setOpCode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional uint64 seq = 4;
 * @return {string}
 */
proto.Message.prototype.getSeq = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, "0"));
};


/**
 * @param {string} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setSeq = function(value) {
  return jspb.Message.setProto3StringIntField(this, 4, value);
};


/**
 * optional AuthRequest auth_request = 11;
 * @return {?proto.AuthRequest}
 */
proto.Message.prototype.getAuthRequest = function() {
  return /** @type{?proto.AuthRequest} */ (
    jspb.Message.getWrapperField(this, Auth_pb.AuthRequest, 11));
};


/**
 * @param {?proto.AuthRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setAuthRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearAuthRequest = function() {
  return this.setAuthRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasAuthRequest = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional AuthAck auth_ack = 12;
 * @return {?proto.AuthAck}
 */
proto.Message.prototype.getAuthAck = function() {
  return /** @type{?proto.AuthAck} */ (
    jspb.Message.getWrapperField(this, Auth_pb.AuthAck, 12));
};


/**
 * @param {?proto.AuthAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setAuthAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearAuthAck = function() {
  return this.setAuthAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasAuthAck = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional MsgRequest msg_request = 20;
 * @return {?proto.MsgRequest}
 */
proto.Message.prototype.getMsgRequest = function() {
  return /** @type{?proto.MsgRequest} */ (
    jspb.Message.getWrapperField(this, Msg_pb.MsgRequest, 20));
};


/**
 * @param {?proto.MsgRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setMsgRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 20, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearMsgRequest = function() {
  return this.setMsgRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasMsgRequest = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional MsgAck msg_ack = 23;
 * @return {?proto.MsgAck}
 */
proto.Message.prototype.getMsgAck = function() {
  return /** @type{?proto.MsgAck} */ (
    jspb.Message.getWrapperField(this, Msg_pb.MsgAck, 23));
};


/**
 * @param {?proto.MsgAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setMsgAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 23, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearMsgAck = function() {
  return this.setMsgAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasMsgAck = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional QueryUserGroupsRequest query_user_group_request = 21;
 * @return {?proto.QueryUserGroupsRequest}
 */
proto.Message.prototype.getQueryUserGroupRequest = function() {
  return /** @type{?proto.QueryUserGroupsRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.QueryUserGroupsRequest, 21));
};


/**
 * @param {?proto.QueryUserGroupsRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setQueryUserGroupRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearQueryUserGroupRequest = function() {
  return this.setQueryUserGroupRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasQueryUserGroupRequest = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional QueryUserGroupsAck query_user_group_ack = 22;
 * @return {?proto.QueryUserGroupsAck}
 */
proto.Message.prototype.getQueryUserGroupAck = function() {
  return /** @type{?proto.QueryUserGroupsAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.QueryUserGroupsAck, 22));
};


/**
 * @param {?proto.QueryUserGroupsAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setQueryUserGroupAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 22, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearQueryUserGroupAck = function() {
  return this.setQueryUserGroupAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasQueryUserGroupAck = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional AskFroJoinGroupRequest ask_for_join_group_request = 24;
 * @return {?proto.AskFroJoinGroupRequest}
 */
proto.Message.prototype.getAskForJoinGroupRequest = function() {
  return /** @type{?proto.AskFroJoinGroupRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.AskFroJoinGroupRequest, 24));
};


/**
 * @param {?proto.AskFroJoinGroupRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setAskForJoinGroupRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 24, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearAskForJoinGroupRequest = function() {
  return this.setAskForJoinGroupRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasAskForJoinGroupRequest = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional AskForJoinGroupAck ask_for_join_group_ack = 25;
 * @return {?proto.AskForJoinGroupAck}
 */
proto.Message.prototype.getAskForJoinGroupAck = function() {
  return /** @type{?proto.AskForJoinGroupAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.AskForJoinGroupAck, 25));
};


/**
 * @param {?proto.AskForJoinGroupAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setAskForJoinGroupAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 25, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearAskForJoinGroupAck = function() {
  return this.setAskForJoinGroupAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasAskForJoinGroupAck = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional InvitationJoinGroupRequest invitation_join_group_request = 26;
 * @return {?proto.InvitationJoinGroupRequest}
 */
proto.Message.prototype.getInvitationJoinGroupRequest = function() {
  return /** @type{?proto.InvitationJoinGroupRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.InvitationJoinGroupRequest, 26));
};


/**
 * @param {?proto.InvitationJoinGroupRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationJoinGroupRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 26, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationJoinGroupRequest = function() {
  return this.setInvitationJoinGroupRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationJoinGroupRequest = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional InvitationJoinGroupAck invitation_join_group_ack = 27;
 * @return {?proto.InvitationJoinGroupAck}
 */
proto.Message.prototype.getInvitationJoinGroupAck = function() {
  return /** @type{?proto.InvitationJoinGroupAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.InvitationJoinGroupAck, 27));
};


/**
 * @param {?proto.InvitationJoinGroupAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationJoinGroupAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 27, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationJoinGroupAck = function() {
  return this.setInvitationJoinGroupAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationJoinGroupAck = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional CreateGroupRequest create_group_request = 28;
 * @return {?proto.CreateGroupRequest}
 */
proto.Message.prototype.getCreateGroupRequest = function() {
  return /** @type{?proto.CreateGroupRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.CreateGroupRequest, 28));
};


/**
 * @param {?proto.CreateGroupRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setCreateGroupRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 28, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearCreateGroupRequest = function() {
  return this.setCreateGroupRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasCreateGroupRequest = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional CreateGroupAck create_group_ack = 29;
 * @return {?proto.CreateGroupAck}
 */
proto.Message.prototype.getCreateGroupAck = function() {
  return /** @type{?proto.CreateGroupAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.CreateGroupAck, 29));
};


/**
 * @param {?proto.CreateGroupAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setCreateGroupAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 29, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearCreateGroupAck = function() {
  return this.setCreateGroupAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasCreateGroupAck = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * optional RemoveGroupMemberRequest remove_group_member_request = 30;
 * @return {?proto.RemoveGroupMemberRequest}
 */
proto.Message.prototype.getRemoveGroupMemberRequest = function() {
  return /** @type{?proto.RemoveGroupMemberRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.RemoveGroupMemberRequest, 30));
};


/**
 * @param {?proto.RemoveGroupMemberRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setRemoveGroupMemberRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 30, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearRemoveGroupMemberRequest = function() {
  return this.setRemoveGroupMemberRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasRemoveGroupMemberRequest = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional RemoveGroupMemberAck remove_group_member_ack = 31;
 * @return {?proto.RemoveGroupMemberAck}
 */
proto.Message.prototype.getRemoveGroupMemberAck = function() {
  return /** @type{?proto.RemoveGroupMemberAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.RemoveGroupMemberAck, 31));
};


/**
 * @param {?proto.RemoveGroupMemberAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setRemoveGroupMemberAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 31, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearRemoveGroupMemberAck = function() {
  return this.setRemoveGroupMemberAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasRemoveGroupMemberAck = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional ChangeGroupNameRequest change_group_name_request = 32;
 * @return {?proto.ChangeGroupNameRequest}
 */
proto.Message.prototype.getChangeGroupNameRequest = function() {
  return /** @type{?proto.ChangeGroupNameRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.ChangeGroupNameRequest, 32));
};


/**
 * @param {?proto.ChangeGroupNameRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setChangeGroupNameRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 32, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearChangeGroupNameRequest = function() {
  return this.setChangeGroupNameRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasChangeGroupNameRequest = function() {
  return jspb.Message.getField(this, 32) != null;
};


/**
 * optional ChangeGroupNameAck change_group_name_ack = 33;
 * @return {?proto.ChangeGroupNameAck}
 */
proto.Message.prototype.getChangeGroupNameAck = function() {
  return /** @type{?proto.ChangeGroupNameAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.ChangeGroupNameAck, 33));
};


/**
 * @param {?proto.ChangeGroupNameAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setChangeGroupNameAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 33, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearChangeGroupNameAck = function() {
  return this.setChangeGroupNameAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasChangeGroupNameAck = function() {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional ChangeGroupNoticeRequest change_group_notice_request = 34;
 * @return {?proto.ChangeGroupNoticeRequest}
 */
proto.Message.prototype.getChangeGroupNoticeRequest = function() {
  return /** @type{?proto.ChangeGroupNoticeRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.ChangeGroupNoticeRequest, 34));
};


/**
 * @param {?proto.ChangeGroupNoticeRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setChangeGroupNoticeRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 34, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearChangeGroupNoticeRequest = function() {
  return this.setChangeGroupNoticeRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasChangeGroupNoticeRequest = function() {
  return jspb.Message.getField(this, 34) != null;
};


/**
 * optional ChangeGroupNoticeAck change_group_notice_ack = 35;
 * @return {?proto.ChangeGroupNoticeAck}
 */
proto.Message.prototype.getChangeGroupNoticeAck = function() {
  return /** @type{?proto.ChangeGroupNoticeAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.ChangeGroupNoticeAck, 35));
};


/**
 * @param {?proto.ChangeGroupNoticeAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setChangeGroupNoticeAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 35, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearChangeGroupNoticeAck = function() {
  return this.setChangeGroupNoticeAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasChangeGroupNoticeAck = function() {
  return jspb.Message.getField(this, 35) != null;
};


/**
 * optional ChangeMucMuteRequest change_muc_mute_request = 36;
 * @return {?proto.ChangeMucMuteRequest}
 */
proto.Message.prototype.getChangeMucMuteRequest = function() {
  return /** @type{?proto.ChangeMucMuteRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.ChangeMucMuteRequest, 36));
};


/**
 * @param {?proto.ChangeMucMuteRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setChangeMucMuteRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 36, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearChangeMucMuteRequest = function() {
  return this.setChangeMucMuteRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasChangeMucMuteRequest = function() {
  return jspb.Message.getField(this, 36) != null;
};


/**
 * optional ChangeMucMuteAck change_muc_mute_ack = 37;
 * @return {?proto.ChangeMucMuteAck}
 */
proto.Message.prototype.getChangeMucMuteAck = function() {
  return /** @type{?proto.ChangeMucMuteAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.ChangeMucMuteAck, 37));
};


/**
 * @param {?proto.ChangeMucMuteAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setChangeMucMuteAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 37, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearChangeMucMuteAck = function() {
  return this.setChangeMucMuteAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasChangeMucMuteAck = function() {
  return jspb.Message.getField(this, 37) != null;
};


/**
 * optional ChangeMucConfirmJoinRequest change_muc_confirm_join_request = 38;
 * @return {?proto.ChangeMucConfirmJoinRequest}
 */
proto.Message.prototype.getChangeMucConfirmJoinRequest = function() {
  return /** @type{?proto.ChangeMucConfirmJoinRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.ChangeMucConfirmJoinRequest, 38));
};


/**
 * @param {?proto.ChangeMucConfirmJoinRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setChangeMucConfirmJoinRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 38, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearChangeMucConfirmJoinRequest = function() {
  return this.setChangeMucConfirmJoinRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasChangeMucConfirmJoinRequest = function() {
  return jspb.Message.getField(this, 38) != null;
};


/**
 * optional ChangeMucConfirmJoinAck change_muc_confirm_join_ack = 39;
 * @return {?proto.ChangeMucConfirmJoinAck}
 */
proto.Message.prototype.getChangeMucConfirmJoinAck = function() {
  return /** @type{?proto.ChangeMucConfirmJoinAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.ChangeMucConfirmJoinAck, 39));
};


/**
 * @param {?proto.ChangeMucConfirmJoinAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setChangeMucConfirmJoinAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 39, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearChangeMucConfirmJoinAck = function() {
  return this.setChangeMucConfirmJoinAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasChangeMucConfirmJoinAck = function() {
  return jspb.Message.getField(this, 39) != null;
};


/**
 * optional ExitGroupRequest exit_group_request = 40;
 * @return {?proto.ExitGroupRequest}
 */
proto.Message.prototype.getExitGroupRequest = function() {
  return /** @type{?proto.ExitGroupRequest} */ (
    jspb.Message.getWrapperField(this, Group_pb.ExitGroupRequest, 40));
};


/**
 * @param {?proto.ExitGroupRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setExitGroupRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 40, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearExitGroupRequest = function() {
  return this.setExitGroupRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasExitGroupRequest = function() {
  return jspb.Message.getField(this, 40) != null;
};


/**
 * optional ExitGroupAck exit_group_ack = 41;
 * @return {?proto.ExitGroupAck}
 */
proto.Message.prototype.getExitGroupAck = function() {
  return /** @type{?proto.ExitGroupAck} */ (
    jspb.Message.getWrapperField(this, Group_pb.ExitGroupAck, 41));
};


/**
 * @param {?proto.ExitGroupAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setExitGroupAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 41, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearExitGroupAck = function() {
  return this.setExitGroupAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasExitGroupAck = function() {
  return jspb.Message.getField(this, 41) != null;
};


/**
 * optional InvitationRequestRequest invitation_request_request = 1001;
 * @return {?proto.InvitationRequestRequest}
 */
proto.Message.prototype.getInvitationRequestRequest = function() {
  return /** @type{?proto.InvitationRequestRequest} */ (
    jspb.Message.getWrapperField(this, Invitation_pb.InvitationRequestRequest, 1001));
};


/**
 * @param {?proto.InvitationRequestRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationRequestRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1001, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationRequestRequest = function() {
  return this.setInvitationRequestRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationRequestRequest = function() {
  return jspb.Message.getField(this, 1001) != null;
};


/**
 * optional InvitationRequestAck invitation_request_ack = 1002;
 * @return {?proto.InvitationRequestAck}
 */
proto.Message.prototype.getInvitationRequestAck = function() {
  return /** @type{?proto.InvitationRequestAck} */ (
    jspb.Message.getWrapperField(this, Invitation_pb.InvitationRequestAck, 1002));
};


/**
 * @param {?proto.InvitationRequestAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationRequestAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1002, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationRequestAck = function() {
  return this.setInvitationRequestAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationRequestAck = function() {
  return jspb.Message.getField(this, 1002) != null;
};


/**
 * optional InvitationAcceptRequest invitation_accept_request = 1003;
 * @return {?proto.InvitationAcceptRequest}
 */
proto.Message.prototype.getInvitationAcceptRequest = function() {
  return /** @type{?proto.InvitationAcceptRequest} */ (
    jspb.Message.getWrapperField(this, Invitation_pb.InvitationAcceptRequest, 1003));
};


/**
 * @param {?proto.InvitationAcceptRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationAcceptRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1003, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationAcceptRequest = function() {
  return this.setInvitationAcceptRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationAcceptRequest = function() {
  return jspb.Message.getField(this, 1003) != null;
};


/**
 * optional InvitationAcceptAck invitation_accept_ack = 1004;
 * @return {?proto.InvitationAcceptAck}
 */
proto.Message.prototype.getInvitationAcceptAck = function() {
  return /** @type{?proto.InvitationAcceptAck} */ (
    jspb.Message.getWrapperField(this, Invitation_pb.InvitationAcceptAck, 1004));
};


/**
 * @param {?proto.InvitationAcceptAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationAcceptAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1004, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationAcceptAck = function() {
  return this.setInvitationAcceptAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationAcceptAck = function() {
  return jspb.Message.getField(this, 1004) != null;
};


/**
 * optional InvitationDeclinedRequest invitation_declined_request = 1005;
 * @return {?proto.InvitationDeclinedRequest}
 */
proto.Message.prototype.getInvitationDeclinedRequest = function() {
  return /** @type{?proto.InvitationDeclinedRequest} */ (
    jspb.Message.getWrapperField(this, Invitation_pb.InvitationDeclinedRequest, 1005));
};


/**
 * @param {?proto.InvitationDeclinedRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationDeclinedRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1005, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationDeclinedRequest = function() {
  return this.setInvitationDeclinedRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationDeclinedRequest = function() {
  return jspb.Message.getField(this, 1005) != null;
};


/**
 * optional InvitationDeclinedAck invitation_declined_ack = 1006;
 * @return {?proto.InvitationDeclinedAck}
 */
proto.Message.prototype.getInvitationDeclinedAck = function() {
  return /** @type{?proto.InvitationDeclinedAck} */ (
    jspb.Message.getWrapperField(this, Invitation_pb.InvitationDeclinedAck, 1006));
};


/**
 * @param {?proto.InvitationDeclinedAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationDeclinedAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1006, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationDeclinedAck = function() {
  return this.setInvitationDeclinedAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationDeclinedAck = function() {
  return jspb.Message.getField(this, 1006) != null;
};


/**
 * optional InvitationRequest invitation_request = 1007;
 * @return {?proto.InvitationRequest}
 */
proto.Message.prototype.getInvitationRequest = function() {
  return /** @type{?proto.InvitationRequest} */ (
    jspb.Message.getWrapperField(this, Invitation_pb.InvitationRequest, 1007));
};


/**
 * @param {?proto.InvitationRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1007, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationRequest = function() {
  return this.setInvitationRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationRequest = function() {
  return jspb.Message.getField(this, 1007) != null;
};


/**
 * optional InvitationAck invitation_ack = 1008;
 * @return {?proto.InvitationAck}
 */
proto.Message.prototype.getInvitationAck = function() {
  return /** @type{?proto.InvitationAck} */ (
    jspb.Message.getWrapperField(this, Invitation_pb.InvitationAck, 1008));
};


/**
 * @param {?proto.InvitationAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setInvitationAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1008, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearInvitationAck = function() {
  return this.setInvitationAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasInvitationAck = function() {
  return jspb.Message.getField(this, 1008) != null;
};


/**
 * optional FriendRequest friend_request = 1009;
 * @return {?proto.FriendRequest}
 */
proto.Message.prototype.getFriendRequest = function() {
  return /** @type{?proto.FriendRequest} */ (
    jspb.Message.getWrapperField(this, Friend_pb.FriendRequest, 1009));
};


/**
 * @param {?proto.FriendRequest|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setFriendRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1009, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearFriendRequest = function() {
  return this.setFriendRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasFriendRequest = function() {
  return jspb.Message.getField(this, 1009) != null;
};


/**
 * optional FriendAck friend_ack = 1010;
 * @return {?proto.FriendAck}
 */
proto.Message.prototype.getFriendAck = function() {
  return /** @type{?proto.FriendAck} */ (
    jspb.Message.getWrapperField(this, Friend_pb.FriendAck, 1010));
};


/**
 * @param {?proto.FriendAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setFriendAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1010, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearFriendAck = function() {
  return this.setFriendAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasFriendAck = function() {
  return jspb.Message.getField(this, 1010) != null;
};


goog.object.extend(exports, proto);
