// package: 
// file: OpCode.proto

import * as jspb from "google-protobuf";

export interface OpCodeMap {
  UNKNOWN: 0;
  AUTH_REQUEST: 1;
  AUTH_ACK: 2;
  MSG_REQUEST: 3;
  MSG_ACK: 33;
  QUERY_USER_GROUP_REQUEST: 4;
  QUERY_USER_GROUP_ACK: 5;
  FRIEND_INVITATION_REQUEST_REQUEST: 1001;
  FRIEND_INVITATION_REQUEST_ACK: 1002;
  FRIEND_INVITATION_ACCEPT_REQUEST: 1003;
  FRIEND_INVITATION_ACCEPT_ACK: 1004;
  FRIEND_INVITATION_DECLINED_REQUEST: 1005;
  FRIEND_INVITATION_DECLINED_ACK: 1006;
  FRIEND_INVITATION_REQUEST: 1007;
  FRIEND_INVITATION_ACK: 1008;
  FRIEND_REQUEST: 1009;
  FRIEND_ACK: 1010;
}

export const OpCode: OpCodeMap;

